namespace BudgetBoard.Service.Models;

public static class TransactionCategoriesConstants
{
    public static readonly IEnumerable<ICategory> DefaultTransactionCategories = new List<ICategory>([
        new CategoryBase {Value = "Auto & Transport", Parent = ""},
        new CategoryBase {Value = "Auto Insurance", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Auto Payment", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Gas & Fuel", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Parking", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Public Transportation", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Ride Share", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Service & Parts", Parent = "Auto & Transport"},
        new CategoryBase {Value = "Bills & Utilities", Parent = ""},
        new CategoryBase {Value = "Internet", Parent = "Bills & Utilities"},
        new CategoryBase {Value = "Mobile Phone", Parent = "Bills & Utilities"},
        new CategoryBase {Value = "Television", Parent = "Bills & Utilities"},
        new CategoryBase {Value = "Utilities", Parent = "Bills & Utilities"},
        new CategoryBase {Value = "Education", Parent = ""},
        new CategoryBase {Value = "Books & Supplies", Parent = "Education"},
        new CategoryBase {Value = "Student Loan", Parent = "Education"},
        new CategoryBase {Value = "Tuition", Parent = "Education"},
        new CategoryBase {Value = "Entertainment", Parent = ""},
        new CategoryBase {Value = "Activities", Parent = "Entertainment"},
        new CategoryBase {Value = "Arts", Parent = "Entertainment"},
        new CategoryBase {Value = "Movies", Parent = "Entertainment"},
        new CategoryBase {Value = "Music", Parent = "Entertainment"},
        new CategoryBase {Value = "Books", Parent = "Entertainment"},
        new CategoryBase {Value = "Games", Parent = "Entertainment"},
        new CategoryBase {Value = "Fees & Charges", Parent = ""},
        new CategoryBase {Value = "ATM Fee", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Bank Fee", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Finance Charge", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Late Fee", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Service Fee", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Trade Commissions", Parent = "Fees & Charges"},
        new CategoryBase {Value = "Financial", Parent = ""},
        new CategoryBase {Value = "Roth IRA", Parent = "Financial"},
        new CategoryBase {Value = "Investment", Parent = "Financial"},
        new CategoryBase {Value = "Food & Dining", Parent = ""},
        new CategoryBase {Value = "Alcohol & Bars", Parent = "Food & Dining"},
        new CategoryBase {Value = "Coffee Shops", Parent = "Food & Dining"},
        new CategoryBase {Value = "Food Delivery", Parent = "Food & Dining"},
        new CategoryBase {Value = "Groceries", Parent = "Food & Dining"},
        new CategoryBase {Value = "Restaurants", Parent = "Food & Dining"},
        new CategoryBase {Value = "Gifts & Donations", Parent = ""},
        new CategoryBase {Value = "Charity", Parent = "Gifts & Donations"},
        new CategoryBase {Value = "Gift", Parent = "Gifts & Donations"},
        new CategoryBase {Value = "Goals", Parent = ""},
        new CategoryBase {Value = "Health & Fitness", Parent = ""},
        new CategoryBase {Value = "Dentist", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Doctor", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Eyecare", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Gym", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Health Insurance", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Pharmacy", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Sports", Parent = "Health & Fitness"},
        new CategoryBase {Value = "Hide from Budgets", Parent = ""},
        new CategoryBase {Value = "Home", Parent = ""},
        new CategoryBase {Value = "Furnishings", Parent = "Home"},
        new CategoryBase {Value = "Home Improvement", Parent = "Home"},
        new CategoryBase {Value = "Home Insurance", Parent = "Home"},
        new CategoryBase {Value = "Home Services", Parent = "Home"},
        new CategoryBase {Value = "Home Supplies", Parent = "Home"},
        new CategoryBase {Value = "Lawn & Garden", Parent = "Home"},
        new CategoryBase {Value = "Mortgage & Rent", Parent = "Home"},
        new CategoryBase {Value = "Income", Parent = ""},
        new CategoryBase {Value = "Bonus", Parent = "Income"},
        new CategoryBase {Value = "Interest Income", Parent = "Income"},
        new CategoryBase {Value = "Paycheck", Parent = "Income"},
        new CategoryBase {Value = "Reimburstments", Parent = "Income"},
        new CategoryBase {Value = "Tax Return", Parent = "Income"},
        new CategoryBase {Value = "Investments", Parent = ""},
        new CategoryBase {Value = "Buy", Parent = "Investments"},
        new CategoryBase {Value = "Deposit", Parent = "Investments"},
        new CategoryBase {Value = "Dividend & Cap Gains", Parent = "Investments"},
        new CategoryBase {Value = "Sell", Parent = "Investments"},
        new CategoryBase {Value = "Withdrawl", Parent = "Investments"},
        new CategoryBase {Value = "Loans", Parent = ""},
        new CategoryBase {Value = "Loan Fees & Charges", Parent = "Loans"},
        new CategoryBase {Value = "Loan Insurance", Parent = "Loans"},
        new CategoryBase {Value = "Loan Interest", Parent = "Loans"},
        new CategoryBase {Value = "Loan Payments", Parent = "Loans"},
        new CategoryBase {Value = "Loan Principal", Parent = "Loans"},
        new CategoryBase {Value = "Misc", Parent = ""},
        new CategoryBase {Value = "Personal Care", Parent = ""},
        new CategoryBase {Value = "Hair", Parent = "Personal Care"},
        new CategoryBase {Value = "Laundry", Parent = "Personal Care"},
        new CategoryBase {Value = "Spa & Massage", Parent = "Personal Care"},
        new CategoryBase {Value = "Pets", Parent = ""},
        new CategoryBase {Value = "Pet Food & Supplies", Parent = "Pets"},
        new CategoryBase {Value = "Pet Grooming", Parent = "Pets"},
        new CategoryBase {Value = "Veterinary", Parent = "Pets"},
        new CategoryBase {Value = "Shopping", Parent = ""},
        new CategoryBase {Value = "Clothing", Parent = "Shopping"},
        new CategoryBase {Value = "Electronics & Software", Parent = "Shopping"},
        new CategoryBase {Value = "Hobbies", Parent = "Shopping"},
        new CategoryBase {Value = "Household", Parent = "Shopping"},
        new CategoryBase {Value = "Taxes", Parent = ""},
        new CategoryBase {Value = "Federal Tax", Parent = "Taxes"},
        new CategoryBase {Value = "Local Tax", Parent = "Taxes"},
        new CategoryBase {Value = "Property Tax", Parent = "Taxes"},
        new CategoryBase {Value = "Sales Tax", Parent = "Taxes"},
        new CategoryBase {Value = "State Tax", Parent = "Taxes"},
        new CategoryBase {Value = "Transfer", Parent = ""},
        new CategoryBase {Value = "Credit Card Payment", Parent = "Transfer"},
        new CategoryBase {Value = "Travel", Parent = ""},
        new CategoryBase {Value = "Air Travel", Parent = "Travel"},
        new CategoryBase {Value = "Hotel", Parent = "Travel"},
        new CategoryBase {Value = "Rental Car & Taxi", Parent = "Travel"},
        new CategoryBase {Value = "Vacation", Parent = "Travel"},
        new CategoryBase {Value = "Other", Parent = ""}
    ]);
}

