services:
  budget-board-server:
    container_name: budget-board-server
    restart: unless-stopped
    image: ghcr.io/teelur/budget-board/server:release
    build: ./server
    environment:
      Logging__LogLevel__Default: Information
      CLIENT_URL: budget-board-client
      POSTGRES_HOST: budget-board-db
      POSTGRES_DATABASE: budgetboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecretPassword
      AUTO_UPDATE_DB: true
    networks:
      - budget-board-network
    depends_on:
      - budget-board-db
  budget-board-client:
    container_name: budget-board-client
    restart: unless-stopped
    image: ghcr.io/teelur/budget-board/client:release
    build: ./client
    environment:
      VITE_API_URL: budget-board-client
      PORT: 6253
    ports:
      - 6253:6253
    networks:
      - budget-board-network
    depends_on:
      - budget-board-server
  budget-board-db:
    container_name: postgres-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecretPassword
      POSTGRES_DB: budgetboard
    ports:
      - "6252:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - budget-board-network

volumes:
  db-data:

networks:
  budget-board-network:
    name: budget-board-network
    driver: bridge
